application: budapestcycletrack
version: 1
runtime: python
api_version: 1

handlers:
- url: /upload
  script: upload.py

- url: /stats
  script: upload.py

- url: /stats/.*
  script: upload.py

- url: /marketplace
  script: redirect.py

- url: /appstore
  script: redirect.py

- url: /iphone_map
  script: iphone_map.py

- url: /(.+)
  static_files: html/\1
  upload: html/(.+)


- url: /
  script: index.py

