application: budapestcycletrack
version: 1
runtime: python
api_version: 1

handlers:
- url: /upload
  script: upload.py

- url: /stats
  script: upload.py

- url: /stats/.*
  script: upload.py

- url: /hello_old_tracks
  script: upload.py

- url: /marketplace
  script: redirect.py

- url: /appstore
  script: redirect.py

- url: /iphone_map
  script: iphone_map.py

- url: /map
  script: iphone_map.py

- url: /embed_map
  script: iphone_map.py

- url: /mapreduce(/.*)?
  script: mapreduce/main.py
  login: admin

- url: /apk
  static_files: html/apk/index.html
  upload: html

- url: /apk/
  static_files: html/apk/index.html
  upload: html2

- url: /qr
  script: upload.py

##################
# maradek url-ek:
##################

- url: /(.+)
  static_files: html/\1
  upload: html/(.+)

- url: /
  script: index.py
